LysisBI/Controllers/ImHereController.cs
using Microsoft.IdentityModel.Clients.ActiveDirectory;
using Microsoft.PowerBI.Api.V2;
using Microsoft.PowerBI.Api.V2.Models;
using Microsoft.Rest;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using LysisBI.Models.Services;
using System;

namespace LysisBI.Controllers
{
    public class ImHereController : Controller
    {
      


        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Login(UsuarioServices usuario)
        {
            if (!usuario.validaAcesso())
            {
                ViewBag.msgErro = "Usuário e/ou Senha incorretos!";
                return View(usuario);

            }
            else

                 if (usuario.TipoUsuario == 0)
            {
                Session["Usuario"] = usuario.NomeUsuario;
                Session["IdProfessor"] = usuario.IdProfessor;
                
                return RedirectToAction("SelecaoTurma");

            }
            else if (usuario.TipoUsuario == 1)
            {

                Session["Usuario"] = usuario.NomeUsuario;
                Session["IdAluno"] = usuario.IdAluno;

                return RedirectToAction("AmbienteAluno");

            }
            else
            {
                return RedirectToAction("Login");
            }

        }

        public ActionResult SelecaoTurma()

        {
            AulaServices aula = new AulaServices();
            aula.Id_professor = (int)(Session["IdProfessor"]);
            aula.ListaDeAulas = aula.listaAula();
            return View(aula);
        }

        public ActionResult AmbienteAluno()

        {
            return View();
        }

        [HttpPost]
        public ActionResult AmbienteAluno(AulaServices aula)

        {
            
            aula.listarDadosAula(aula.Token);
            Session["IdAula"]= aula.Id_aula;
            Session["Disciplina"] = aula.Disciplina;
            Session["Turma"] = aula.Dsc_turma;
            Session["Turno"] = aula.Turno;
            Session["Professor"] = aula.Nome_professor;
            Session["Token"] = aula.Token;


            AlunoServices aluno = new AlunoServices();
            aluno.obterDadosAluno((int)(Session["IdAluno"]));
            Session["NomeAluno"] = aluno.NomeAluno;
            Session["Matricula"] = aluno.MatriculaAluno;
            return RedirectToAction("ConfirmacaoDados");
        }

        public ActionResult ConfirmacaoDados()

        {

            return View();
        }


        [HttpPost]
        public ActionResult EfetivarPresenca()

        {
            
            FrequenciaServices frequencia = new FrequenciaServices();

            
            frequencia.IdAula = (int)(Session["IdAula"]);
            frequencia.IdAluno = (int)(Session["IdAluno"]);
            frequencia.MatriculaAluno = (string)(Session["Matricula"]); ;
            frequencia.NomeAluno = (string)(Session["NomeAluno"]); ;
            frequencia.DataHoraRegistro = DateTime.Now;
            frequencia.Presenca = true;
            frequencia.TokenUtilizado = (string)(Session["Token"]);

            frequencia.inserirPresenca();


            return RedirectToAction("Exito");
        }

        
        public ActionResult Exito()

        {
            return View();

        }

        [HttpPost]
        public ActionResult Logout()

        {
            Session["NomeAluno"] = null;
            Session["Matricula"] = null;
            Session["IdAula"] = null;
            Session["Disciplina"] = null;
            Session["Turma"] = null;
            Session["Turno"] = null;
            Session["Professor"] = null;
            Session["Token"] = null;
            Session["Usuario"] = null;
            Session["IdAluno"] = null;
            Session["IdProfessor"] = null;

            return RedirectToAction("Login");

        }



    }

    }

LysisBI/Views/ImHere/AmbienteAluno.cshtml
@model LysisBI.Models.Services.AulaServices


<html>
<head>
    <title></title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="~/Content/dashboard/assets/css/main.css" />
    <link rel="stylesheet" href="/Content/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/login/assets/css/main.css" />
</head>
<body>
    <div id="page-wrapper">

        <!-- Header -->
        <section id="header" class="wrapper">

            <!-- Logo -->
            <div id="logo">
                <h1>I'm Here!</h1>
                <p>Unifametro</p>
            </div>

            <!-- Nav -->
            <nav id="nav">

                <ul>
                    <li>
                        <a href="#">Olá,&nbsp;@Session["Usuario"]</a>
                        <ul>
                            <li><a href="#">Sobre</a></li>
                            <li><a href="#">Sair</a></li>


                        </ul>
                    </li>
                </ul>
            </nav>

        </section>
    </div>

    <div id="divPrincipal" class="container" align="center">
        <br />
        <br />
        <div id="divPrincipal" class="box" align="center">
            @using (Html.BeginForm())

            {

                <div class="fields" href="~/Content/login/assets/css/main.css">
                    <br />
                    
                        @Html.TextBoxFor(m => m.Token, new { @placeholder = "Insira o token", @align = "center" })
                        <br />


                </div>

                <ul class="actions stacked">
                    <li><input type="submit" value="Validar" class="button bg-success" /> </li>
                </ul>
            }

        </div>

        </div>


        <!-- Scripts     -->
        <script src="~/Content/dashboard/assets/js/jquery.min.js"></script>
        <script src="~/Content/dashboard/assets/js/jquery.dropotron.min.js"></script>
        <script src="~/Content/dashboard/assets/js/browser.min.js"></script>
        <script src="~/Content/dashboard/assets/js/breakpoints.min.js"></script>
        <script src="~/Content/dashboard/assets/js/util.js"></script>
        <script src="~/Content/dashboard/assets/js/main.js"></script>

</body>
</html>

LysisBI/Views/ImHere/ConfirmacaoDados.cshtml
<html>
<head>
    <title>I'm Here!</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="~/Content/dashboard/assets/css/main.css" />
    <link rel="stylesheet" href="/Content/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/login/assets/css/main.css" />


</head>
<body>
    <div id="page-wrapper">

        <!-- Header -->
        <section id="header" class="wrapper">

            <!-- Logo -->
            <div id="logo">
                <h1>I'm Here!</h1>
                <p>Unifametro</p>
            </div>

            <!-- Nav -->
            <nav id="nav">

                <ul>
                    <li>
                        <a href="#">Olá,&nbsp;@Session["Usuario"]</a>
                        <ul>
                            <li><a href="#">Sobre</a></li>
                            <li><a href="#">Sair</a></li>

                        </ul>
                    </li>
                </ul>
            </nav>

        </section>
    </div>

    
    <div id="divContainer" class="container">
        
            <div class="card">
                <div class="card-header bg-success">Dados da aula para confirmação</div>
                <div class="card-block">
                    <br />
                    <div class="row">
                        
                        <label>&nbsp;Aluno: @Session["NomeAluno"]</label>
                        
                    </div>
                   
                    <div class="row">
                        
                        <label>&nbsp;Matrícula: @Session["Matricula"]</label>
                        
                    </div>

                    <div class="row">
                        
                        <label>&nbsp;Disciplina: @Session["Disciplina"]</label>
                        
                    </div>
                    <div class="row">
                        
                        <label>&nbsp;Turma: @Session["Turma"]</label>
                        
                    </div>
                    <div class="row">
                        
                        <label>&nbsp;Turno: @Session["Turno"]</label>
                        
                    </div>
                    <div class="row">
                        
                        <label>&nbsp;Professor: @Session["Professor"]</label>
                        
                    </div>

                </div>

            </div>
            <br />



            @using (Html.BeginForm("EfetivarPresenca", "ImHere", new { id = "form1122" }))
            {
                <div id="botaoConfirmacao">

                    <input type="submit" value="I'm Here!" class="button bg-success" />


                </div>
            }


    </div>

    <!-- Scripts     -->
    <script src="~/Content/dashboard/assets/js/jquery.min.js"></script>
    <script src="~/Content/dashboard/assets/js/jquery.dropotron.min.js"></script>
    <script src="~/Content/dashboard/assets/js/browser.min.js"></script>
    <script src="~/Content/dashboard/assets/js/breakpoints.min.js"></script>
    <script src="~/Content/dashboard/assets/js/util.js"></script>
    <script src="~/Content/dashboard/assets/js/main.js"></script>



</body>
</html>

LysisBI/Views/ImHere/Exito.cshtml
<html>
<head>
    <title>I'm Here!</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="~/Content/dashboard/assets/css/main.css" />
    <link rel="stylesheet" href="/Content/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/login/assets/css/main.css" />

</head>
<body>
    <div id="page-wrapper">

        <!-- Header -->
        <section id="header" class="wrapper">

            <!-- Logo -->
            <div id="logo">
                <h1>You're Here!</h1>
                <p>Unifametro</p>
            </div>

            <!-- Nav -->
            <nav id="nav">

                <ul>
                    <li>
                        <a href="#">Olá,&nbsp;@Session["Usuario"]</a>
                        <ul>
                            <li><a href="#">Sobre</a></li>
                            <li><a href="#">Sair</a></li>

                        </ul>
                    </li>
                </ul>
            </nav>

        </section>
    </div>

    <div id="divPrincipal" class="container">
        <br />
        <div class="box">

            &nbsp;@Session["NomeAluno"]<br />
            &nbsp;Você registrou sua presença na aula de<br />
            &nbsp; @Session["Disciplina"]<br />
            &nbsp;do professor(a)&nbsp; @Session["Professor"]<br />
            <br />
            &nbsp;**Caso queira, pode tirar um print para registro**
            
        </div>

        @using (Html.BeginForm("Logout", "ImHere", new { id = "form1122" }))
        {
            <div id="botaoFinalizar" align="center">

                <input type="submit" value="Finalizar!" class="btn bg-success" />
            </div>
        }

    </div>

   



    <!-- Scripts     -->
    <script src="~/Content/dashboard/assets/js/jquery.min.js"></script>
    <script src="~/Content/dashboard/assets/js/jquery.dropotron.min.js"></script>
    <script src="~/Content/dashboard/assets/js/browser.min.js"></script>
    <script src="~/Content/dashboard/assets/js/breakpoints.min.js"></script>
    <script src="~/Content/dashboard/assets/js/util.js"></script>
    <script src="~/Content/dashboard/assets/js/main.js"></script>




</body>
</html>

LysisBI/Views/ImHere/Login.cshtml
@model LysisBI.Models.Services.UsuarioServices

@{
    ViewBag.Title = "Index";
    Layout = null;
}


<!DOCTYPE HTML>
<html>
<head>
    <title>I'm Here!</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="~/Content/login/assets/css/main.css" />
    <noscript><link rel="stylesheet" href="~/Content/login/assets/css/noscript.css" /></noscript>
</head>
<body class="is-preload">

 
    <div id="wrapper" class="divided">


        <section class="banner style1 orient-left content-align-left image-position-right fullscreen onload-image-fade-in onload-content-fade-right">
            <div class="content">
               
                <h2>I'm Here!</h2>
                

                @using (Html.BeginForm())

                {
                <div class="fields">
                    <div class="field half">
                        @Html.TextBoxFor(m => m.UsuarioDigitado, new { @class = "field half", @placeholder = "Usuário" })
                        <br />
                   
                        @Html.TextBoxFor(m => m.SenhaDigitada, new { @class = "field halfl", @placeholder = "Senha", type = "password" })

                    </div>
                </div>
                
                    <ul class="actions stacked">
                        <li><input type="submit" value="OK" class="button big wide smooth-scroll-middle" /> </li>
                    </ul>
                    }

                </div>
                    <div class="image">
                        <img src="~/Content/login/images/banner.jpg" />
                    </div>

</section>
    </div>


    <!-- Scripts -->
    <script src="~/Content/login/assets/js/jquery.min.js"></script>
    <script src="~/Content/login/assets/js/jquery.scrollex.min.js"></script>
    <script src="~/Content/login/assets/js/jquery.scrolly.min.js"></script>
    <script src="~/Content/login/assets/js/browser.min.js"></script>
    <script src="~/Content/login/assets/js/breakpoints.min.js"></script>
    <script src="~/Content/login/assets/js/util.js"></script>
    <script src="~/Content/login/assets/js/main.js"></script>
  
</body>
</html>

LysisBI/Views/ImHere/SelecaoTurma.cshtml
@model LysisBI.Models.Services.AulaServices


<html>
<head>
    <title>I'm Here!</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="~/Content/dashboard/assets/css/main.css" />
    <link rel="stylesheet" href="/Content/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/login/assets/css/main.css" />
</head>
<body>
    <div id="page-wrapper">

        <!-- Header -->
        <section id="header" class="wrapper">

            <!-- Logo -->
            <div id="logo">
                <h1>I'm Here!</h1>
                <p>Unifametro</p>
            </div>

            <!-- Nav -->
            <nav id="nav">

                <ul>
                    <li>
                        <a href="#">Olá,&nbsp;@Session["Usuario"]</a>
                        <ul>
                            <li><a href="#">Sobre</a></li>
                            <li><a href="#">Sair</a></li>

                        </ul>
                    </li>
                </ul>
            </nav>

        </section>
    </div>
    <br />

    <div id="divPrincipal" class="container">

        <div class="card">
            <div class="card-header bg-success">Professor(a), selecione a aula</div>
            <br />

            @using (Html.BeginForm("SelecaoTurma", "ImHereController", FormMethod.Post, new { id = "form11" }))


            {
                @Html.CheckBoxFor(m => m.Selected)
                foreach (var item in Model.ListaDeAulas)
                {


                    <div class="card-block">

                        <div class="row">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox"
                                           name="SelectedAula"
                                           checked=@item.Selected
                                           value="@item.Value" /> &nbsp;@item.Text
                                    </label>
                                </div>

                            </div>
                        </div>
                    }
                    <br />
                    <div id="botaoFinalizar" align="center">

                        <input type="submit" value="Selecionar" class="btn bg-success" />
                    </div>
                }

        </div>
       

        </div>

    <!-- Scripts     -->
    <script src="~/Content/dashboard/assets/js/jquery.min.js"></script>
    <script src="~/Content/dashboard/assets/js/jquery.dropotron.min.js"></script>
    <script src="~/Content/dashboard/assets/js/browser.min.js"></script>
    <script src="~/Content/dashboard/assets/js/breakpoints.min.js"></script>
    <script src="~/Content/dashboard/assets/js/util.js"></script>
    <script src="~/Content/dashboard/assets/js/main.js"></script>


</body>
</html>